// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFOk456UlQeUiuKgp5TuD3l186eGZtFVc',
    appId: '1:516911058445:android:71f50eeba7ec3078d38f44',
    messagingSenderId: '516911058445',
    projectId: 'n-a-c-39adb',
    databaseURL: 'https://n-a-c-39adb.firebaseio.com',
    storageBucket: 'n-a-c-39adb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVQMd6Q3MaZec5lpvY5mrRpq20grZdM2o',
    appId: '1:516911058445:ios:ba7485a070d547ffd38f44',
    messagingSenderId: '516911058445',
    projectId: 'n-a-c-39adb',
    databaseURL: 'https://n-a-c-39adb.firebaseio.com',
    storageBucket: 'n-a-c-39adb.appspot.com',
    iosClientId: '516911058445-ioh4225pvdo49gcbp3kb0oqhl2gt4j7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.crictalk',
  );
}
